# -*- coding: utf-8 -*-

"""
    Mappings
"""

country_map = {'': '',
    ('Bonaire, Sint Eustatius and Saba','BQ'): 'base.bq',
    ('Curaçao','CW'): 'base.cw',
    ('Hong Kong','HK'): 'base.hk',
    ('South Sudan','SS'): 'base.ss',
    ('Sint Maarten (Dutch)','SX'): 'base.sx',
    ('Timor-Leste','TL'): 'base.tl',
    ('Andorra','AD'): 'base.ad',
    ('United Arab Emirates','AE'): 'base.ae',
    ('Afghanistan','AF'): 'base.af',
    ('Antigua and Barbuda','AG'): 'base.ag',
    ('Anguilla','AI'): 'base.ai',
    ('Albania','AL'): 'base.al',
    ('Armenia','AM'): 'base.am',
    ('Angola','AO'): 'base.ao',
    ('Antarctica','AQ'): 'base.aq',
    ('Argentina','AR'): 'base.ar',
    ('American Samoa','AS'): 'base.as',
    ('Austria','AT'): 'base.at',
    ('Australia','AU'): 'base.au',
    ('Aruba','AW'): 'base.aw',
    ('Åland Islands','AX'): 'base.ax',
    ('Azerbaijan','AZ'): 'base.az',
    ('Bosnia and Herzegovina','BA'): 'base.ba',
    ('Barbados','BB'): 'base.bb',
    ('Bangladesh','BD'): 'base.bd',
    ('Belgium','BE'): 'base.be',
    ('Burkina Faso','BF'): 'base.bf',
    ('Bulgaria','BG'): 'base.bg',
    ('Bahrain','BH'): 'base.bh',
    ('Burundi','BI'): 'base.bi',
    ('Benin','BJ'): 'base.bj',
    ('Saint Barthélémy','BL'): 'base.bl',
    ('Bermuda','BM'): 'base.bm',
    ('Brunei Darussalam','BN'): 'base.bn',
    ('Bolivia','BO'): 'base.bo',
    ('Brazil','BR'): 'base.br',
    ('Bahamas','BS'): 'base.bs',
    ('Bhutan','BT'): 'base.bt',
    ('Bouvet Island','BV'): 'base.bv',
    ('Botswana','BW'): 'base.bw',
    ('Belarus','BY'): 'base.by',
    ('Belize','BZ'): 'base.bz',
    ('Canada','CA'): 'base.ca',
    ('Cocos (Keeling) Islands','CC'): 'base.cc',
    ('Democratic Republic of the Congo','CD'): 'base.cd',
    ('Central African Republic','CF'): 'base.cf',
    ('Congo','CG'): 'base.cg',
    ('Switzerland','CH'): 'base.ch',
    ('Côte d''Ivoire','CI'): 'base.ci',
    ('Cook Islands','CK'): 'base.ck',
    ('Chile','CL'): 'base.cl',
    ('Cameroon','CM'): 'base.cm',
    ('China','CN'): 'base.cn',
    ('Colombia','CO'): 'base.co',
    ('Costa Rica','CR'): 'base.cr',
    ('Cuba','CU'): 'base.cu',
    ('Cape Verde','CV'): 'base.cv',
    ('Christmas Island','CX'): 'base.cx',
    ('Cyprus','CY'): 'base.cy',
    ('Czech Republic','CZ'): 'base.cz',
    ('Germany','DE'): 'base.de',
    ('Djibouti','DJ'): 'base.dj',
    ('Denmark','DK'): 'base.dk',
    ('Dominica','DM'): 'base.dm',
    ('Dominican Republic','DO'): 'base.do',
    ('Algeria','DZ'): 'base.dz',
    ('Ecuador','EC'): 'base.ec',
    ('Estonia','EE'): 'base.ee',
    ('Egypt','EG'): 'base.eg',
    ('Western Sahara','EH'): 'base.eh',
    ('Eritrea','ER'): 'base.er',
    ('Spain','ES'): 'base.es',
    ('Ethiopia','ET'): 'base.et',
    ('Finland','FI'): 'base.fi',
    ('Fiji','FJ'): 'base.fj',
    ('Falkland Islands','FK'): 'base.fk',
    ('Micronesia','FM'): 'base.fm',
    ('Faroe Islands','FO'): 'base.fo',
    ('France','FR'): 'base.fr',
    ('Gabon','GA'): 'base.ga',
    ('United Kingdom','GB'): 'base.gb',
    ('Grenada','GD'): 'base.gd',
    ('Georgia','GE'): 'base.ge',
    ('French Guiana','GF'): 'base.gf',
    ('Guernsey','GG'): 'base.gg',
    ('Ghana','GH'): 'base.gh',
    ('Gibraltar','GI'): 'base.gi',
    ('Greenland','GL'): 'base.gl',
    ('Gambia','GM'): 'base.gm',
    ('Guinea','GN'): 'base.gn',
    ('Guadeloupe','GP'): 'base.gp',
    ('Equatorial Guinea','GQ'): 'base.gq',
    ('Greece','GR'): 'base.gr',
    ('South Georgia and the South Sandwich Islands','GS'): 'base.gs',
    ('Guatemala','GT'): 'base.gt',
    ('Guam','GU'): 'base.gu',
    ('Guinea-Bissau','GW'): 'base.gw',
    ('Guyana','GY'): 'base.gy',
    ('Heard Island and McDonald Islands','HM'): 'base.hm',
    ('Honduras','HN'): 'base.hn',
    ('Croatia','HR'): 'base.hr',
    ('Haiti','HT'): 'base.ht',
    ('Hungary','HU'): 'base.hu',
    ('Indonesia','ID'): 'base.id',
    ('Ireland','IE'): 'base.ie',
    ('Israel','IL'): 'base.il',
    ('Isle of Man','IM'): 'base.im',
    ('India','IN'): 'base.in',
    ('British Indian Ocean Territory','IO'): 'base.io',
    ('Iraq','IQ'): 'base.iq',
    ('Iran','IR'): 'base.ir',
    ('Iceland','IS'): 'base.is',
    ('Italy','IT'): 'base.it',
    ('Jersey','JE'): 'base.je',
    ('Jamaica','JM'): 'base.jm',
    ('Jordan','JO'): 'base.jo',
    ('Japan','JP'): 'base.jp',
    ('Kenya','KE'): 'base.ke',
    ('Kyrgyzstan','KG'): 'base.kg',
    ('Cambodia','KH'): 'base.kh',
    ('Kiribati','KI'): 'base.ki',
    ('Comoros','KM'): 'base.km',
    ('Saint Kitts and Nevis','KN'): 'base.kn',
    ('North Korea','KP'): 'base.kp',
    ('South Korea','KR'): 'base.kr',
    ('Kuwait','KW'): 'base.kw',
    ('Cayman Islands','KY'): 'base.ky',
    ('Kazakhstan','KZ'): 'base.kz',
    ('Laos','LA'): 'base.la',
    ('Lebanon','LB'): 'base.lb',
    ('Saint Lucia','LC'): 'base.lc',
    ('Liechtenstein','LI'): 'base.li',
    ('Sri Lanka','LK'): 'base.lk',
    ('Liberia','LR'): 'base.lr',
    ('Lesotho','LS'): 'base.ls',
    ('Lithuania','LT'): 'base.lt',
    ('Luxembourg','LU'): 'base.lu',
    ('Latvia','LV'): 'base.lv',
    ('Libya','LY'): 'base.ly',
    ('Morocco','MA'): 'base.ma',
    ('Monaco','MC'): 'base.mc',
    ('Moldova','MD'): 'base.md',
    ('Montenegro','ME'): 'base.me',
    ('Saint Martin (French part)','MF'): 'base.mf',
    ('Madagascar','MG'): 'base.mg',
    ('Marshall Islands','MH'): 'base.mh',
    ('Macedonia, the former Yugoslav Republic of','MK'): 'base.mk',
    ('Mali','ML'): 'base.ml',
    ('Myanmar','MM'): 'base.mm',
    ('Mongolia','MN'): 'base.mn',
    ('Macau','MO'): 'base.mo',
    ('Northern Mariana Islands','MP'): 'base.mp',
    ('Martinique','MQ'): 'base.mq',
    ('Mauritania','MR'): 'base.mr',
    ('Montserrat','MS'): 'base.ms',
    ('Malta','MT'): 'base.mt',
    ('Mauritius','MU'): 'base.mu',
    ('Maldives','MV'): 'base.mv',
    ('Malawi','MW'): 'base.mw',
    ('Mexico','MX'): 'base.mx',
    ('Malaysia','MY'): 'base.my',
    ('Mozambique','MZ'): 'base.mz',
    ('Namibia','NA'): 'base.na',
    ('New Caledonia','NC'): 'base.nc',
    ('Niger','NE'): 'base.ne',
    ('Norfolk Island','NF'): 'base.nf',
    ('Nigeria','NG'): 'base.ng',
    ('Nicaragua','NI'): 'base.ni',
    ('Netherlands','NL'): 'base.nl',
    ('Norway','NO'): 'base.no',
    ('Nepal','NP'): 'base.np',
    ('Nauru','NR'): 'base.nr',
    ('Niue','NU'): 'base.nu',
    ('New Zealand','NZ'): 'base.nz',
    ('Oman','OM'): 'base.om',
    ('Panama','PA'): 'base.pa',
    ('Peru','PE'): 'base.pe',
    ('French Polynesia','PF'): 'base.pf',
    ('Papua New Guinea','PG'): 'base.pg',
    ('Philippines','PH'): 'base.ph',
    ('Pakistan','PK'): 'base.pk',
    ('Poland','PL'): 'base.pl',
    ('Saint Pierre and Miquelon','PM'): 'base.pm',
    ('Pitcairn Islands','PN'): 'base.pn',
    ('Puerto Rico','PR'): 'base.pr',
    ('State of Palestine','PS'): 'base.ps',
    ('Portugal','PT'): 'base.pt',
    ('Palau','PW'): 'base.pw',
    ('Paraguay','PY'): 'base.py',
    ('Qatar','QA'): 'base.qa',
    ('Réunion','RE'): 'base.re',
    ('Romania','RO'): 'base.ro',
    ('Serbia','RS'): 'base.rs',
    ('Russian Federation','RU'): 'base.ru',
    ('Rwanda','RW'): 'base.rw',
    ('Saudi Arabia','SA'): 'base.sa',
    ('Solomon Islands','SB'): 'base.sb',
    ('Seychelles','SC'): 'base.sc',
    ('Sudan','SD'): 'base.sd',
    ('Sweden','SE'): 'base.se',
    ('Singapore','SG'): 'base.sg',
    ('Saint Helena, Ascension and Tristan da Cunha','SH'): 'base.sh',
    ('Slovenia','SI'): 'base.si',
    ('Svalbard and Jan Mayen','SJ'): 'base.sj',
    ('Slovakia','SK'): 'base.sk',
    ('Sierra Leone','SL'): 'base.sl',
    ('San Marino','SM'): 'base.sm',
    ('Senegal','SN'): 'base.sn',
    ('Somalia','SO'): 'base.so',
    ('Suriname','SR'): 'base.sr',
    ('São Tomé and Príncipe','ST'): 'base.st',
    ('El Salvador','SV'): 'base.sv',
    ('Syria','SY'): 'base.sy',
    ('Swaziland','SZ'): 'base.sz',
    ('Turks and Caicos Islands','TC'): 'base.tc',
    ('Chad','TD'): 'base.td',
    ('French Southern Territories','TF'): 'base.tf',
    ('Togo','TG'): 'base.tg',
    ('Thailand','TH'): 'base.th',
    ('Tajikistan','TJ'): 'base.tj',
    ('Tokelau','TK'): 'base.tk',
    ('Turkmenistan','TM'): 'base.tm',
    ('Tunisia','TN'): 'base.tn',
    ('Tonga','TO'): 'base.to',
    ('Turkey','TR'): 'base.tr',
    ('Trinidad and Tobago','TT'): 'base.tt',
    ('Tuvalu','TV'): 'base.tv',
    ('Taiwan','TW'): 'base.tw',
    ('Tanzania','TZ'): 'base.tz',
    ('Ukraine','UA'): 'base.ua',
    ('Uganda','UG'): 'base.ug',
    ('USA Minor Outlying Islands','UM'): 'base.um',
    ('United States','US'): 'base.us',
    ('Uruguay','UY'): 'base.uy',
    ('Uzbekistan','UZ'): 'base.uz',
    ('Holy See (Vatican City State)','VA'): 'base.va',
    ('Saint Vincent and the Grenadines','VC'): 'base.vc',
    ('Venezuela','VE'): 'base.ve',
    ('Virgin Islands (British)','VG'): 'base.vg',
    ('Virgin Islands (USA)','VI'): 'base.vi',
    ('Vietnam','VN'): 'base.vn',
    ('Vanuatu','VU'): 'base.vu',
    ('Wallis and Futuna','WF'): 'base.wf',
    ('Samoa','WS'): 'base.ws',
    ('Yemen','YE'): 'base.ye',
    ('Mayotte','YT'): 'base.yt',
    ('South Africa','ZA'): 'base.za',
    ('Zambia','ZM'): 'base.zm',
    ('Zimbabwe','ZW'): 'base.zw',
}

lang_map = {'': '',
    ('Kabyle','Taqbaylit','kab'): 'en_US',
    ('Khmer','ភាសាខ្មែរ','km'): 'am_ET',
    ('Amharic','አምሃርኛ','am_ET'): 'ar_SY',
    ('Arabic','الْعَرَبيّة','ar_SY'): 'eu_ES',
    ('Basque','Euskara','eu_ES'): 'bs_BA',
    ('Bosnian','bosanski jezik','bs'): 'bg_BG',
    ('Bulgarian','български език','bg'): 'ca_ES',
    ('Catalan','Català','ca_ES'): 'zh_CN',
    ('Chinese','CN','简体中文','zh_CN'): 'zh_HK',
    ('Chinese','HK','zh_HK'): 'zh_TW',
    ('Chinese','TW','正體字','zh_TW'): 'hr_HR',
    ('Croatian','hrvatski jezik','hr'): 'cs_CZ',
    ('Czech','Čeština','cs_CZ'): 'da_DK',
    ('Danish','Dansk','da_DK'): 'nl_BE',
    ('Dutch','BE','Nederlands','BE','nl_BE'): 'nl_NL',
    ('Dutch','Nederlands','nl'): 'en_AU',
    ('English','AU','en_AU'): 'en_GB',
    ('English','UK','en_GB'): 'et_EE',
    ('Estonian','Eesti keel','et'): 'fi_FI',
    ('Finnish','Suomi','fi'): 'fr_BE',
    ('French','BE','Français','BE','fr_BE'): 'fr_CA',
    ('French','CA','Français','CA','fr_CA'): 'fr_CH',
    ('French','CH','Français','CH','fr_CH'): 'fr_FR',
    ('French','Français','fr'): 'gl_ES',
    ('Galician','Galego','gl'): 'ka_GE',
    ('Georgian','ქართული ენა','ka'): 'de_DE',
    ('German','Deutsch','de'): 'de_CH',
    ('German','CH','Deutsch','CH','de_CH'): 'el_GR',
    ('Greek','Ελληνικά','el_GR'): 'gu_IN',
    ('Gujarati','ગુજરાતી','gu'): 'he_IL',
    ('Hebrew','עִבְרִי','he'): 'hi_IN',
    ('Hindi','हिंदी','hi'): 'hu_HU',
    ('Hungarian','Magyar','hu'): 'id_ID',
    ('Indonesian','Bahasa Indonesia','id'): 'it_IT',
    ('Italian','Italiano','it'): 'ja_JP',
    ('Japanese','日本語','ja'): 'kab_DZ',
    ('Korean','KP','한국어','KP','ko_KP'): 'km_KM',
    ('Korean','KR','한국어','KR','ko_KR'): 'ko_KP',
    ('Lao','ພາສາລາວ','lo'): 'ko_KR',
    ('Latvian','latviešu valoda','lv'): 'lo_LA',
    ('Lithuanian','Lietuvių kalba','lt'): 'lv_LV',
    ('Macedonian','македонски јазик','mk'): 'lt_LT',
    ('Mongolian','монгол','mn'): 'mk_MK',
    ('Burmese','ဗမာစာ','my'): 'mn_MN',
    ('Norwegian Bokmål','Norsk bokmål','nb_NO'): 'my_MM',
    ('Persian','فارس','fa'): 'nb_NO',
    ('Polish','Język polski','pl'): 'fa_IR',
    ('Portuguese','BR','Português','BR','pt_BR'): 'pl_PL',
    ('Portuguese','Português','pt'): 'pt_BR',
    ('Romanian','română','ro'): 'pt_PT',
    ('Russian','русский язык','ru'): 'ro_RO',
    ('Serbian','Cyrillic','српски','sr_RS'): 'ru_RU',
    ('Serbian','Latin','srpski','sr@latin'): 'sr_RS',
    ('Slovak','Slovenský jazyk','sk'): 'sr@latin',
    ('Slovenian','slovenščina','sl'): 'sk_SK',
    ('Spanish','AR','Español','AR','es_AR'): 'sl_SI',
    ('Spanish','BO','Español','BO','es_BO'): 'es_AR',
    ('Spanish','CL','Español','CL','es_CL'): 'es_BO',
    ('Spanish','CO','Español','CO','es_CO'): 'es_CL',
    ('Spanish','CR','Español','CR','es_CR'): 'es_CO',
    ('Spanish','DO','Español','DO','es_DO'): 'es_CR',
    ('Spanish','EC','Español','EC','es_EC'): 'es_DO',
    ('Spanish','GT','Español','GT','es_GT'): 'es_EC',
    ('Spanish','MX','Español','MX','es_MX'): 'es_GT',
    ('Spanish','PA','Español','PA','es_PA'): 'es_MX',
    ('Spanish','PE','Español','PE','es_PE'): 'es_PA',
    ('Spanish','PY','Español','PY','es_PY'): 'es_PE',
    ('Spanish','UY','Español','UY','es_UY'): 'es_PY',
    ('Spanish','VE','Español','VE','es_VE'): 'es_UY',
    ('Spanish','Español','es'): 'es_VE',
    ('Swedish','svenska','sv'): 'es_ES',
    ('Thai','ภาษาไทย','th'): 'sv_SE',
    ('Turkish','Türkçe','tr'): 'th_TH',
    ('Ukrainian','українська','uk'): 'tr_TR',
    ('Vietnamese','Tiếng Việt','vi'): 'uk_UA',
    ('Albanian','Shqip','sq'): 'vi_VN',
    ('Telugu','తెలుగు','te'): 'sq_AL',
    ('English','en'): 'te_IN',
}

website_map = {'': '',
    'AWWEA': '1',
    'Merciao': '2',
    'Mystic': '3',
    'GPI': '4',
}
