# -*- coding: utf-8 -*-

TEMPLATE_PREFIX = 'PRODUCT_TEMPLATE'
PRODUCT_PREFIX = 'PRODUCT_PRODUCT'
CATEGORY_PREFIX = 'PRODUCT_CATEGORY'
PUB_CATEGORY_PREFIX = 'PUB_PRODUCT_CATEGORY'

PRODUCT_SUPPLIER_PREFIX = 'PRODUCT_SUPPLIERINFO'
PARTNER_SUPPLIER_PREFIX = 'PARTNER_SUPPLIER'
PRODUCT_BRAND_PREFIX = 'PRODUCT_BRAND'

VAR_IMAGE_PREFIX = 'PRODUCT_IMAGE'
IMAGE_PREFIX = 'TEMPLATE_IMAGE'
IMAGE_URL_PREFIX = 'IMAGE_URL'

ATTRIBUTE_PREFIX = 'PRODUCT_ATTRIBUTE'
ATTRIBUTE_LINE_PREFIX = 'PRODUCT_ATTRIBUTE_LINE'
ATTRIBUTE_VALUE_PREFIX = 'PRODUCT_ATTRIBUTE_VALUE'
